"""create comment table

Revision ID: 48e3b8fb0825
Revises: 9eb384b92b8c
Create Date: 2019-01-11 17:43:39.592440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e3b8fb0825'
down_revision = '9eb384b92b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'id')
    # ### end Alembic commands ###
