"""update Img table

Revision ID: 7d48516944e3
Revises: 067846340cbf
Create Date: 2019-01-11 16:41:41.119810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d48516944e3'
down_revision = '067846340cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imgs', sa.Column('comment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imgs', 'comment')
    # ### end Alembic commands ###
