"""create comment table

Revision ID: 9eb384b92b8c
Revises: 5f2eeeeb7fd0
Create Date: 2019-01-11 17:29:28.098398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb384b92b8c'
down_revision = '5f2eeeeb7fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
