"""create comment table

Revision ID: d72feaded1d4
Revises: 81bcd31b9588
Create Date: 2019-01-11 17:11:38.439644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72feaded1d4'
down_revision = '81bcd31b9588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'create_time')
    # ### end Alembic commands ###
