"""change_like

Revision ID: de86b1026686
Revises: 8ceb8caf7f80
Create Date: 2019-03-07 17:00:24.170161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de86b1026686'
down_revision = '8ceb8caf7f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
